backend:
  name: git-gateway
  branch: master 

media_folder: "static/uploads" 
public_folder: "/uploads"

collections:
  - name: "posts" 
    label: "Posts" 
    folder: "content" 
    create: true 
    slug: "{{slug}}" 
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Sadržaj", name: "content", widget: "markdown" }
