#static/admin/config.yml

backend:
  name: git-gateway
  branch: master
locale: "hr" # Language code for localization
media_folder: "static/img"
collections:
  - name: "posts" 
    label: "Objave" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum objave", name: "date", widget: "datetime" }
      - { label: "Slika", name: "image", widget: "image" }
      - { label: "Oznake", name: "tags", widget: "list", summary: "{{fields.tag}}", field: { label: "Tag", name: "tag", widget: "string" }} # https://github.com/decaporg/decap-cms/issues/4646 
      - { label: "Sadržaj", name: "body", widget: "markdown", hint: "Ne zaboravi dodati popratnu sliku!" }
    sortable_fields: ['date', 'title', 'commit_author']
