#static/admin/config.yml

backend:
  name: git-gateway
  branch: master
locale: "hr" # Language code for localization
format: "yaml" 
media_folder: "static/img" # Path where uploaded media files are stored
public_folder: "/img"      # Public URL path for the media files
collections:
  - name: "posts"
    label: "Objave" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - label: "Naslov"
        name: "title"
        widget: "string"

      - label: "Datum objave"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD" 

      - label: "Slike"
        name: "images"
        widget: "list"
        field:
          label: "Slika"
          name: "image"
          widget: "image"

      - label: "Sadržaj"
        name: "body"
        widget: "markdown"
        hint: "Molim nešto kreativno"